import { Inter } from 'next/font/google'
import './globals.css'
// app/layout.tsx
import { Providers } from "./providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="ligth text-foreground bg-background">
            {children}

          </main>
        </Providers>
      </body>
    </html>
  )
}
